/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as GuestAboutRouteImport } from './routes/_guest/about'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestPrivacyRouteImport } from './routes/_guest/privacy'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestSupportRouteImport } from './routes/_guest/support'
import { Route as GuestTermsRouteImport } from './routes/_guest/terms'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as AuthAppGrowthRouteRouteImport } from './routes/_auth/app/growth/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppAnalyticsIndexRouteImport } from './routes/_auth/app/analytics/index'
import { Route as AuthAppAppointmentsIndexRouteImport } from './routes/_auth/app/appointments/index'
import { Route as AuthAppAppointmentsIdRouteImport } from './routes/_auth/app/appointments/$id'
import { Route as AuthAppAppointmentsNewRouteImport } from './routes/_auth/app/appointments/new'
import { Route as AuthAppEncountersIndexRouteImport } from './routes/_auth/app/encounters/index'
import { Route as AuthAppEncountersIdRouteImport } from './routes/_auth/app/encounters/$id'
import { Route as AuthAppEncountersNewRouteImport } from './routes/_auth/app/encounters/new'
import { Route as AuthAppGrowthIndexRouteImport } from './routes/_auth/app/growth/index'
import { Route as AuthAppGrowthNewRouteImport } from './routes/_auth/app/growth/new'
import { Route as AuthAppGrowthRecordRouteImport } from './routes/_auth/app/growth/record'
import { Route as AuthAppImmunizationsIndexRouteImport } from './routes/_auth/app/immunizations/index'
import { Route as AuthAppImmunizationsIdRouteImport } from './routes/_auth/app/immunizations/$id'
import { Route as AuthAppImmunizationsNewRouteImport } from './routes/_auth/app/immunizations/new'
import { Route as AuthAppLabsIndexRouteImport } from './routes/_auth/app/labs/index'
import { Route as AuthAppLabsNewRouteImport } from './routes/_auth/app/labs/new'
import { Route as AuthAppPatientsIndexRouteImport } from './routes/_auth/app/patients/index'
import { Route as AuthAppPatientsPatientIdRouteRouteImport } from './routes/_auth/app/patients/$patientId/route'
import { Route as AuthAppPatientsPatientIdRouteImport } from './routes/_auth/app/patients/$patientId'
import { Route as AuthAppPatientsNewRouteImport } from './routes/_auth/app/patients/new'
import { Route as AuthAppPrescriptionsIndexRouteImport } from './routes/_auth/app/prescriptions/index'
import { Route as AuthAppPrescriptionsNewRouteImport } from './routes/_auth/app/prescriptions/new'
import { Route as AuthAppServicesIndexRouteImport } from './routes/_auth/app/services/index'
import { Route as AuthAppSettingsIndexRouteImport } from './routes/_auth/app/settings/index'
import { Route as AuthAppStaffIndexRouteImport } from './routes/_auth/app/staff/index'
import { Route as AuthAppStaffNewRouteImport } from './routes/_auth/app/staff/new'
import { Route as AuthAppVitalsIndexRouteImport } from './routes/_auth/app/vitals/index'
import { Route as AuthAppVitalsNewRouteImport } from './routes/_auth/app/vitals/new'
import { Route as AuthAppAppointmentsIdEditRouteImport } from './routes/_auth/app/appointments/$id.edit'
import { Route as AuthAppEncountersEncounterIdIndexRouteImport } from './routes/_auth/app/encounters/$encounterId/index'
import { Route as AuthAppEncountersEncounterIdEditRouteImport } from './routes/_auth/app/encounters/$encounterId/edit'
import { Route as AuthAppEncountersIdEditRouteImport } from './routes/_auth/app/encounters/$id.edit'
import { Route as AuthAppImmunizationsIdEditRouteImport } from './routes/_auth/app/immunizations/$id.edit'
import { Route as AuthAppImmunizationsImmunizationIdIndexRouteImport } from './routes/_auth/app/immunizations/$immunizationId/index'
import { Route as AuthAppImmunizationsImmunizationIdEditRouteImport } from './routes/_auth/app/immunizations/$immunizationId/edit'
import { Route as AuthAppLabsLabOrderIdIndexRouteImport } from './routes/_auth/app/labs/$labOrderId/index'
import { Route as AuthAppLabsLabOrderIdEditRouteImport } from './routes/_auth/app/labs/$labOrderId/edit'
import { Route as AuthAppPatientsPatientIdEditRouteImport } from './routes/_auth/app/patients/$patientId/edit'
import { Route as AuthAppPatientsPatientIdEncountersRouteImport } from './routes/_auth/app/patients/$patientId/encounters'
import { Route as AuthAppPatientsPatientIdGrowthRouteRouteImport } from './routes/_auth/app/patients/$patientId/growth/route'
import { Route as AuthAppPatientsPatientIdImmunizationsRouteImport } from './routes/_auth/app/patients/$patientId/immunizations'
import { Route as AuthAppPatientsPatientIdLabsRouteImport } from './routes/_auth/app/patients/$patientId/labs'
import { Route as AuthAppPatientsPatientIdPrescriptionsRouteImport } from './routes/_auth/app/patients/$patientId/prescriptions'
import { Route as AuthAppPatientsPatientIdVitalsRouteImport } from './routes/_auth/app/patients/$patientId/vitals'
import { Route as AuthAppPrescriptionsIdEditRouteImport } from './routes/_auth/app/prescriptions/$id.edit'
import { Route as AuthAppPrescriptionsPrescriptionIdIndexRouteImport } from './routes/_auth/app/prescriptions/$prescriptionId/index'
import { Route as AuthAppPrescriptionsPrescriptionIdEditRouteImport } from './routes/_auth/app/prescriptions/$prescriptionId/edit'
import { Route as AuthAppStaffStaffIdIndexRouteImport } from './routes/_auth/app/staff/$staffId/index'
import { Route as AuthAppStaffStaffIdEditRouteImport } from './routes/_auth/app/staff/$staffId/edit'
import { Route as AuthAppPatientsPatientIdGrowthIndexRouteImport } from './routes/_auth/app/patients/$patientId/growth/index'
import { Route as AuthAppPatientsPatientIdGrowthHistoryRouteImport } from './routes/_auth/app/patients/$patientId/growth/history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestAboutRoute = GuestAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestPrivacyRoute = GuestPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSupportRoute = GuestSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestTermsRoute = GuestTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => GuestRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppGrowthRouteRoute = AuthAppGrowthRouteRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppAnalyticsIndexRoute = AuthAppAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppAppointmentsIndexRoute =
  AuthAppAppointmentsIndexRouteImport.update({
    id: '/appointments/',
    path: '/appointments/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppAppointmentsIdRoute = AuthAppAppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppAppointmentsNewRoute = AuthAppAppointmentsNewRouteImport.update({
  id: '/appointments/new',
  path: '/appointments/new',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppEncountersIndexRoute = AuthAppEncountersIndexRouteImport.update({
  id: '/encounters/',
  path: '/encounters/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppEncountersIdRoute = AuthAppEncountersIdRouteImport.update({
  id: '/encounters/$id',
  path: '/encounters/$id',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppEncountersNewRoute = AuthAppEncountersNewRouteImport.update({
  id: '/encounters/new',
  path: '/encounters/new',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppGrowthIndexRoute = AuthAppGrowthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppGrowthRouteRoute,
} as any)
const AuthAppGrowthNewRoute = AuthAppGrowthNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthAppGrowthRouteRoute,
} as any)
const AuthAppGrowthRecordRoute = AuthAppGrowthRecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => AuthAppGrowthRouteRoute,
} as any)
const AuthAppImmunizationsIndexRoute =
  AuthAppImmunizationsIndexRouteImport.update({
    id: '/immunizations/',
    path: '/immunizations/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppImmunizationsIdRoute = AuthAppImmunizationsIdRouteImport.update({
  id: '/immunizations/$id',
  path: '/immunizations/$id',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppImmunizationsNewRoute = AuthAppImmunizationsNewRouteImport.update({
  id: '/immunizations/new',
  path: '/immunizations/new',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppLabsIndexRoute = AuthAppLabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppLabsNewRoute = AuthAppLabsNewRouteImport.update({
  id: '/labs/new',
  path: '/labs/new',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppPatientsIndexRoute = AuthAppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppPatientsPatientIdRouteRoute =
  AuthAppPatientsPatientIdRouteRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppPatientsPatientIdRoute =
  AuthAppPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppPatientsNewRoute = AuthAppPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppPrescriptionsIndexRoute =
  AuthAppPrescriptionsIndexRouteImport.update({
    id: '/prescriptions/',
    path: '/prescriptions/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppPrescriptionsNewRoute = AuthAppPrescriptionsNewRouteImport.update({
  id: '/prescriptions/new',
  path: '/prescriptions/new',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppServicesIndexRoute = AuthAppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppSettingsIndexRoute = AuthAppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppStaffIndexRoute = AuthAppStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppStaffNewRoute = AuthAppStaffNewRouteImport.update({
  id: '/staff/new',
  path: '/staff/new',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppVitalsIndexRoute = AuthAppVitalsIndexRouteImport.update({
  id: '/vitals/',
  path: '/vitals/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppVitalsNewRoute = AuthAppVitalsNewRouteImport.update({
  id: '/vitals/new',
  path: '/vitals/new',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppAppointmentsIdEditRoute =
  AuthAppAppointmentsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthAppAppointmentsIdRoute,
  } as any)
const AuthAppEncountersEncounterIdIndexRoute =
  AuthAppEncountersEncounterIdIndexRouteImport.update({
    id: '/encounters/$encounterId/',
    path: '/encounters/$encounterId/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppEncountersEncounterIdEditRoute =
  AuthAppEncountersEncounterIdEditRouteImport.update({
    id: '/encounters/$encounterId/edit',
    path: '/encounters/$encounterId/edit',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppEncountersIdEditRoute = AuthAppEncountersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthAppEncountersIdRoute,
} as any)
const AuthAppImmunizationsIdEditRoute =
  AuthAppImmunizationsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthAppImmunizationsIdRoute,
  } as any)
const AuthAppImmunizationsImmunizationIdIndexRoute =
  AuthAppImmunizationsImmunizationIdIndexRouteImport.update({
    id: '/immunizations/$immunizationId/',
    path: '/immunizations/$immunizationId/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppImmunizationsImmunizationIdEditRoute =
  AuthAppImmunizationsImmunizationIdEditRouteImport.update({
    id: '/immunizations/$immunizationId/edit',
    path: '/immunizations/$immunizationId/edit',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppLabsLabOrderIdIndexRoute =
  AuthAppLabsLabOrderIdIndexRouteImport.update({
    id: '/labs/$labOrderId/',
    path: '/labs/$labOrderId/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppLabsLabOrderIdEditRoute =
  AuthAppLabsLabOrderIdEditRouteImport.update({
    id: '/labs/$labOrderId/edit',
    path: '/labs/$labOrderId/edit',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppPatientsPatientIdEditRoute =
  AuthAppPatientsPatientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthAppPatientsPatientIdRoute,
  } as any)
const AuthAppPatientsPatientIdEncountersRoute =
  AuthAppPatientsPatientIdEncountersRouteImport.update({
    id: '/encounters',
    path: '/encounters',
    getParentRoute: () => AuthAppPatientsPatientIdRoute,
  } as any)
const AuthAppPatientsPatientIdGrowthRouteRoute =
  AuthAppPatientsPatientIdGrowthRouteRouteImport.update({
    id: '/growth',
    path: '/growth',
    getParentRoute: () => AuthAppPatientsPatientIdRoute,
  } as any)
const AuthAppPatientsPatientIdImmunizationsRoute =
  AuthAppPatientsPatientIdImmunizationsRouteImport.update({
    id: '/immunizations',
    path: '/immunizations',
    getParentRoute: () => AuthAppPatientsPatientIdRoute,
  } as any)
const AuthAppPatientsPatientIdLabsRoute =
  AuthAppPatientsPatientIdLabsRouteImport.update({
    id: '/labs',
    path: '/labs',
    getParentRoute: () => AuthAppPatientsPatientIdRoute,
  } as any)
const AuthAppPatientsPatientIdPrescriptionsRoute =
  AuthAppPatientsPatientIdPrescriptionsRouteImport.update({
    id: '/prescriptions',
    path: '/prescriptions',
    getParentRoute: () => AuthAppPatientsPatientIdRoute,
  } as any)
const AuthAppPatientsPatientIdVitalsRoute =
  AuthAppPatientsPatientIdVitalsRouteImport.update({
    id: '/vitals',
    path: '/vitals',
    getParentRoute: () => AuthAppPatientsPatientIdRoute,
  } as any)
const AuthAppPrescriptionsIdEditRoute =
  AuthAppPrescriptionsIdEditRouteImport.update({
    id: '/prescriptions/$id/edit',
    path: '/prescriptions/$id/edit',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppPrescriptionsPrescriptionIdIndexRoute =
  AuthAppPrescriptionsPrescriptionIdIndexRouteImport.update({
    id: '/prescriptions/$prescriptionId/',
    path: '/prescriptions/$prescriptionId/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppPrescriptionsPrescriptionIdEditRoute =
  AuthAppPrescriptionsPrescriptionIdEditRouteImport.update({
    id: '/prescriptions/$prescriptionId/edit',
    path: '/prescriptions/$prescriptionId/edit',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppStaffStaffIdIndexRoute =
  AuthAppStaffStaffIdIndexRouteImport.update({
    id: '/staff/$staffId/',
    path: '/staff/$staffId/',
    getParentRoute: () => AuthAppRouteRoute,
  } as any)
const AuthAppStaffStaffIdEditRoute = AuthAppStaffStaffIdEditRouteImport.update({
  id: '/staff/$staffId/edit',
  path: '/staff/$staffId/edit',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppPatientsPatientIdGrowthIndexRoute =
  AuthAppPatientsPatientIdGrowthIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthAppPatientsPatientIdGrowthRouteRoute,
  } as any)
const AuthAppPatientsPatientIdGrowthHistoryRoute =
  AuthAppPatientsPatientIdGrowthHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthAppPatientsPatientIdGrowthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/about': typeof GuestAboutRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/privacy': typeof GuestPrivacyRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/signup': typeof GuestSignupRoute
  '/support': typeof GuestSupportRoute
  '/terms': typeof GuestTermsRoute
  '/api/health': typeof ApiHealthRoute
  '/app/growth': typeof AuthAppGrowthRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/patients/$patientId': typeof AuthAppPatientsPatientIdRouteWithChildren
  '/app/appointments/$id': typeof AuthAppAppointmentsIdRouteWithChildren
  '/app/appointments/new': typeof AuthAppAppointmentsNewRoute
  '/app/encounters/$id': typeof AuthAppEncountersIdRouteWithChildren
  '/app/encounters/new': typeof AuthAppEncountersNewRoute
  '/app/growth/new': typeof AuthAppGrowthNewRoute
  '/app/growth/record': typeof AuthAppGrowthRecordRoute
  '/app/immunizations/$id': typeof AuthAppImmunizationsIdRouteWithChildren
  '/app/immunizations/new': typeof AuthAppImmunizationsNewRoute
  '/app/labs/new': typeof AuthAppLabsNewRoute
  '/app/patients/new': typeof AuthAppPatientsNewRoute
  '/app/prescriptions/new': typeof AuthAppPrescriptionsNewRoute
  '/app/staff/new': typeof AuthAppStaffNewRoute
  '/app/vitals/new': typeof AuthAppVitalsNewRoute
  '/app/analytics/': typeof AuthAppAnalyticsIndexRoute
  '/app/appointments/': typeof AuthAppAppointmentsIndexRoute
  '/app/encounters/': typeof AuthAppEncountersIndexRoute
  '/app/growth/': typeof AuthAppGrowthIndexRoute
  '/app/immunizations/': typeof AuthAppImmunizationsIndexRoute
  '/app/labs/': typeof AuthAppLabsIndexRoute
  '/app/patients/': typeof AuthAppPatientsIndexRoute
  '/app/prescriptions/': typeof AuthAppPrescriptionsIndexRoute
  '/app/services/': typeof AuthAppServicesIndexRoute
  '/app/settings/': typeof AuthAppSettingsIndexRoute
  '/app/staff/': typeof AuthAppStaffIndexRoute
  '/app/vitals/': typeof AuthAppVitalsIndexRoute
  '/app/patients/$patientId/growth': typeof AuthAppPatientsPatientIdGrowthRouteRouteWithChildren
  '/app/appointments/$id/edit': typeof AuthAppAppointmentsIdEditRoute
  '/app/encounters/$encounterId/edit': typeof AuthAppEncountersEncounterIdEditRoute
  '/app/encounters/$id/edit': typeof AuthAppEncountersIdEditRoute
  '/app/immunizations/$id/edit': typeof AuthAppImmunizationsIdEditRoute
  '/app/immunizations/$immunizationId/edit': typeof AuthAppImmunizationsImmunizationIdEditRoute
  '/app/labs/$labOrderId/edit': typeof AuthAppLabsLabOrderIdEditRoute
  '/app/patients/$patientId/edit': typeof AuthAppPatientsPatientIdEditRoute
  '/app/patients/$patientId/encounters': typeof AuthAppPatientsPatientIdEncountersRoute
  '/app/patients/$patientId/immunizations': typeof AuthAppPatientsPatientIdImmunizationsRoute
  '/app/patients/$patientId/labs': typeof AuthAppPatientsPatientIdLabsRoute
  '/app/patients/$patientId/prescriptions': typeof AuthAppPatientsPatientIdPrescriptionsRoute
  '/app/patients/$patientId/vitals': typeof AuthAppPatientsPatientIdVitalsRoute
  '/app/prescriptions/$id/edit': typeof AuthAppPrescriptionsIdEditRoute
  '/app/prescriptions/$prescriptionId/edit': typeof AuthAppPrescriptionsPrescriptionIdEditRoute
  '/app/staff/$staffId/edit': typeof AuthAppStaffStaffIdEditRoute
  '/app/encounters/$encounterId/': typeof AuthAppEncountersEncounterIdIndexRoute
  '/app/immunizations/$immunizationId/': typeof AuthAppImmunizationsImmunizationIdIndexRoute
  '/app/labs/$labOrderId/': typeof AuthAppLabsLabOrderIdIndexRoute
  '/app/prescriptions/$prescriptionId/': typeof AuthAppPrescriptionsPrescriptionIdIndexRoute
  '/app/staff/$staffId/': typeof AuthAppStaffStaffIdIndexRoute
  '/app/patients/$patientId/growth/history': typeof AuthAppPatientsPatientIdGrowthHistoryRoute
  '/app/patients/$patientId/growth/': typeof AuthAppPatientsPatientIdGrowthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/builder': typeof BuilderRoute
  '/about': typeof GuestAboutRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/privacy': typeof GuestPrivacyRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/signup': typeof GuestSignupRoute
  '/support': typeof GuestSupportRoute
  '/terms': typeof GuestTermsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/patients/$patientId': typeof AuthAppPatientsPatientIdRouteWithChildren
  '/app/appointments/$id': typeof AuthAppAppointmentsIdRouteWithChildren
  '/app/appointments/new': typeof AuthAppAppointmentsNewRoute
  '/app/encounters/$id': typeof AuthAppEncountersIdRouteWithChildren
  '/app/encounters/new': typeof AuthAppEncountersNewRoute
  '/app/growth/new': typeof AuthAppGrowthNewRoute
  '/app/growth/record': typeof AuthAppGrowthRecordRoute
  '/app/immunizations/$id': typeof AuthAppImmunizationsIdRouteWithChildren
  '/app/immunizations/new': typeof AuthAppImmunizationsNewRoute
  '/app/labs/new': typeof AuthAppLabsNewRoute
  '/app/patients/new': typeof AuthAppPatientsNewRoute
  '/app/prescriptions/new': typeof AuthAppPrescriptionsNewRoute
  '/app/staff/new': typeof AuthAppStaffNewRoute
  '/app/vitals/new': typeof AuthAppVitalsNewRoute
  '/app/analytics': typeof AuthAppAnalyticsIndexRoute
  '/app/appointments': typeof AuthAppAppointmentsIndexRoute
  '/app/encounters': typeof AuthAppEncountersIndexRoute
  '/app/growth': typeof AuthAppGrowthIndexRoute
  '/app/immunizations': typeof AuthAppImmunizationsIndexRoute
  '/app/labs': typeof AuthAppLabsIndexRoute
  '/app/patients': typeof AuthAppPatientsIndexRoute
  '/app/prescriptions': typeof AuthAppPrescriptionsIndexRoute
  '/app/services': typeof AuthAppServicesIndexRoute
  '/app/settings': typeof AuthAppSettingsIndexRoute
  '/app/staff': typeof AuthAppStaffIndexRoute
  '/app/vitals': typeof AuthAppVitalsIndexRoute
  '/app/appointments/$id/edit': typeof AuthAppAppointmentsIdEditRoute
  '/app/encounters/$encounterId/edit': typeof AuthAppEncountersEncounterIdEditRoute
  '/app/encounters/$id/edit': typeof AuthAppEncountersIdEditRoute
  '/app/immunizations/$id/edit': typeof AuthAppImmunizationsIdEditRoute
  '/app/immunizations/$immunizationId/edit': typeof AuthAppImmunizationsImmunizationIdEditRoute
  '/app/labs/$labOrderId/edit': typeof AuthAppLabsLabOrderIdEditRoute
  '/app/patients/$patientId/edit': typeof AuthAppPatientsPatientIdEditRoute
  '/app/patients/$patientId/encounters': typeof AuthAppPatientsPatientIdEncountersRoute
  '/app/patients/$patientId/immunizations': typeof AuthAppPatientsPatientIdImmunizationsRoute
  '/app/patients/$patientId/labs': typeof AuthAppPatientsPatientIdLabsRoute
  '/app/patients/$patientId/prescriptions': typeof AuthAppPatientsPatientIdPrescriptionsRoute
  '/app/patients/$patientId/vitals': typeof AuthAppPatientsPatientIdVitalsRoute
  '/app/prescriptions/$id/edit': typeof AuthAppPrescriptionsIdEditRoute
  '/app/prescriptions/$prescriptionId/edit': typeof AuthAppPrescriptionsPrescriptionIdEditRoute
  '/app/staff/$staffId/edit': typeof AuthAppStaffStaffIdEditRoute
  '/app/encounters/$encounterId': typeof AuthAppEncountersEncounterIdIndexRoute
  '/app/immunizations/$immunizationId': typeof AuthAppImmunizationsImmunizationIdIndexRoute
  '/app/labs/$labOrderId': typeof AuthAppLabsLabOrderIdIndexRoute
  '/app/prescriptions/$prescriptionId': typeof AuthAppPrescriptionsPrescriptionIdIndexRoute
  '/app/staff/$staffId': typeof AuthAppStaffStaffIdIndexRoute
  '/app/patients/$patientId/growth/history': typeof AuthAppPatientsPatientIdGrowthHistoryRoute
  '/app/patients/$patientId/growth': typeof AuthAppPatientsPatientIdGrowthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/builder': typeof BuilderRoute
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/about': typeof GuestAboutRoute
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/privacy': typeof GuestPrivacyRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_guest/support': typeof GuestSupportRoute
  '/_guest/terms': typeof GuestTermsRoute
  '/api/health': typeof ApiHealthRoute
  '/_auth/app/growth': typeof AuthAppGrowthRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/patients/$patientId': typeof AuthAppPatientsPatientIdRouteWithChildren
  '/_auth/app/appointments/$id': typeof AuthAppAppointmentsIdRouteWithChildren
  '/_auth/app/appointments/new': typeof AuthAppAppointmentsNewRoute
  '/_auth/app/encounters/$id': typeof AuthAppEncountersIdRouteWithChildren
  '/_auth/app/encounters/new': typeof AuthAppEncountersNewRoute
  '/_auth/app/growth/new': typeof AuthAppGrowthNewRoute
  '/_auth/app/growth/record': typeof AuthAppGrowthRecordRoute
  '/_auth/app/immunizations/$id': typeof AuthAppImmunizationsIdRouteWithChildren
  '/_auth/app/immunizations/new': typeof AuthAppImmunizationsNewRoute
  '/_auth/app/labs/new': typeof AuthAppLabsNewRoute
  '/_auth/app/patients/new': typeof AuthAppPatientsNewRoute
  '/_auth/app/prescriptions/new': typeof AuthAppPrescriptionsNewRoute
  '/_auth/app/staff/new': typeof AuthAppStaffNewRoute
  '/_auth/app/vitals/new': typeof AuthAppVitalsNewRoute
  '/_auth/app/analytics/': typeof AuthAppAnalyticsIndexRoute
  '/_auth/app/appointments/': typeof AuthAppAppointmentsIndexRoute
  '/_auth/app/encounters/': typeof AuthAppEncountersIndexRoute
  '/_auth/app/growth/': typeof AuthAppGrowthIndexRoute
  '/_auth/app/immunizations/': typeof AuthAppImmunizationsIndexRoute
  '/_auth/app/labs/': typeof AuthAppLabsIndexRoute
  '/_auth/app/patients/': typeof AuthAppPatientsIndexRoute
  '/_auth/app/prescriptions/': typeof AuthAppPrescriptionsIndexRoute
  '/_auth/app/services/': typeof AuthAppServicesIndexRoute
  '/_auth/app/settings/': typeof AuthAppSettingsIndexRoute
  '/_auth/app/staff/': typeof AuthAppStaffIndexRoute
  '/_auth/app/vitals/': typeof AuthAppVitalsIndexRoute
  '/_auth/app/patients/$patientId/growth': typeof AuthAppPatientsPatientIdGrowthRouteRouteWithChildren
  '/_auth/app/appointments/$id/edit': typeof AuthAppAppointmentsIdEditRoute
  '/_auth/app/encounters/$encounterId/edit': typeof AuthAppEncountersEncounterIdEditRoute
  '/_auth/app/encounters/$id/edit': typeof AuthAppEncountersIdEditRoute
  '/_auth/app/immunizations/$id/edit': typeof AuthAppImmunizationsIdEditRoute
  '/_auth/app/immunizations/$immunizationId/edit': typeof AuthAppImmunizationsImmunizationIdEditRoute
  '/_auth/app/labs/$labOrderId/edit': typeof AuthAppLabsLabOrderIdEditRoute
  '/_auth/app/patients/$patientId/edit': typeof AuthAppPatientsPatientIdEditRoute
  '/_auth/app/patients/$patientId/encounters': typeof AuthAppPatientsPatientIdEncountersRoute
  '/_auth/app/patients/$patientId/immunizations': typeof AuthAppPatientsPatientIdImmunizationsRoute
  '/_auth/app/patients/$patientId/labs': typeof AuthAppPatientsPatientIdLabsRoute
  '/_auth/app/patients/$patientId/prescriptions': typeof AuthAppPatientsPatientIdPrescriptionsRoute
  '/_auth/app/patients/$patientId/vitals': typeof AuthAppPatientsPatientIdVitalsRoute
  '/_auth/app/prescriptions/$id/edit': typeof AuthAppPrescriptionsIdEditRoute
  '/_auth/app/prescriptions/$prescriptionId/edit': typeof AuthAppPrescriptionsPrescriptionIdEditRoute
  '/_auth/app/staff/$staffId/edit': typeof AuthAppStaffStaffIdEditRoute
  '/_auth/app/encounters/$encounterId/': typeof AuthAppEncountersEncounterIdIndexRoute
  '/_auth/app/immunizations/$immunizationId/': typeof AuthAppImmunizationsImmunizationIdIndexRoute
  '/_auth/app/labs/$labOrderId/': typeof AuthAppLabsLabOrderIdIndexRoute
  '/_auth/app/prescriptions/$prescriptionId/': typeof AuthAppPrescriptionsPrescriptionIdIndexRoute
  '/_auth/app/staff/$staffId/': typeof AuthAppStaffStaffIdIndexRoute
  '/_auth/app/patients/$patientId/growth/history': typeof AuthAppPatientsPatientIdGrowthHistoryRoute
  '/_auth/app/patients/$patientId/growth/': typeof AuthAppPatientsPatientIdGrowthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/builder'
    | '/app'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/api/health'
    | '/app/growth'
    | '/api/auth/$'
    | '/app/'
    | '/app/patients/$patientId'
    | '/app/appointments/$id'
    | '/app/appointments/new'
    | '/app/encounters/$id'
    | '/app/encounters/new'
    | '/app/growth/new'
    | '/app/growth/record'
    | '/app/immunizations/$id'
    | '/app/immunizations/new'
    | '/app/labs/new'
    | '/app/patients/new'
    | '/app/prescriptions/new'
    | '/app/staff/new'
    | '/app/vitals/new'
    | '/app/analytics/'
    | '/app/appointments/'
    | '/app/encounters/'
    | '/app/growth/'
    | '/app/immunizations/'
    | '/app/labs/'
    | '/app/patients/'
    | '/app/prescriptions/'
    | '/app/services/'
    | '/app/settings/'
    | '/app/staff/'
    | '/app/vitals/'
    | '/app/patients/$patientId/growth'
    | '/app/appointments/$id/edit'
    | '/app/encounters/$encounterId/edit'
    | '/app/encounters/$id/edit'
    | '/app/immunizations/$id/edit'
    | '/app/immunizations/$immunizationId/edit'
    | '/app/labs/$labOrderId/edit'
    | '/app/patients/$patientId/edit'
    | '/app/patients/$patientId/encounters'
    | '/app/patients/$patientId/immunizations'
    | '/app/patients/$patientId/labs'
    | '/app/patients/$patientId/prescriptions'
    | '/app/patients/$patientId/vitals'
    | '/app/prescriptions/$id/edit'
    | '/app/prescriptions/$prescriptionId/edit'
    | '/app/staff/$staffId/edit'
    | '/app/encounters/$encounterId/'
    | '/app/immunizations/$immunizationId/'
    | '/app/labs/$labOrderId/'
    | '/app/prescriptions/$prescriptionId/'
    | '/app/staff/$staffId/'
    | '/app/patients/$patientId/growth/history'
    | '/app/patients/$patientId/growth/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/builder'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/support'
    | '/terms'
    | '/api/health'
    | '/api/auth/$'
    | '/app'
    | '/app/patients/$patientId'
    | '/app/appointments/$id'
    | '/app/appointments/new'
    | '/app/encounters/$id'
    | '/app/encounters/new'
    | '/app/growth/new'
    | '/app/growth/record'
    | '/app/immunizations/$id'
    | '/app/immunizations/new'
    | '/app/labs/new'
    | '/app/patients/new'
    | '/app/prescriptions/new'
    | '/app/staff/new'
    | '/app/vitals/new'
    | '/app/analytics'
    | '/app/appointments'
    | '/app/encounters'
    | '/app/growth'
    | '/app/immunizations'
    | '/app/labs'
    | '/app/patients'
    | '/app/prescriptions'
    | '/app/services'
    | '/app/settings'
    | '/app/staff'
    | '/app/vitals'
    | '/app/appointments/$id/edit'
    | '/app/encounters/$encounterId/edit'
    | '/app/encounters/$id/edit'
    | '/app/immunizations/$id/edit'
    | '/app/immunizations/$immunizationId/edit'
    | '/app/labs/$labOrderId/edit'
    | '/app/patients/$patientId/edit'
    | '/app/patients/$patientId/encounters'
    | '/app/patients/$patientId/immunizations'
    | '/app/patients/$patientId/labs'
    | '/app/patients/$patientId/prescriptions'
    | '/app/patients/$patientId/vitals'
    | '/app/prescriptions/$id/edit'
    | '/app/prescriptions/$prescriptionId/edit'
    | '/app/staff/$staffId/edit'
    | '/app/encounters/$encounterId'
    | '/app/immunizations/$immunizationId'
    | '/app/labs/$labOrderId'
    | '/app/prescriptions/$prescriptionId'
    | '/app/staff/$staffId'
    | '/app/patients/$patientId/growth/history'
    | '/app/patients/$patientId/growth'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/builder'
    | '/_auth/app'
    | '/_guest/about'
    | '/_guest/forgot-password'
    | '/_guest/login'
    | '/_guest/privacy'
    | '/_guest/reset-password'
    | '/_guest/signup'
    | '/_guest/support'
    | '/_guest/terms'
    | '/api/health'
    | '/_auth/app/growth'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/patients/$patientId'
    | '/_auth/app/appointments/$id'
    | '/_auth/app/appointments/new'
    | '/_auth/app/encounters/$id'
    | '/_auth/app/encounters/new'
    | '/_auth/app/growth/new'
    | '/_auth/app/growth/record'
    | '/_auth/app/immunizations/$id'
    | '/_auth/app/immunizations/new'
    | '/_auth/app/labs/new'
    | '/_auth/app/patients/new'
    | '/_auth/app/prescriptions/new'
    | '/_auth/app/staff/new'
    | '/_auth/app/vitals/new'
    | '/_auth/app/analytics/'
    | '/_auth/app/appointments/'
    | '/_auth/app/encounters/'
    | '/_auth/app/growth/'
    | '/_auth/app/immunizations/'
    | '/_auth/app/labs/'
    | '/_auth/app/patients/'
    | '/_auth/app/prescriptions/'
    | '/_auth/app/services/'
    | '/_auth/app/settings/'
    | '/_auth/app/staff/'
    | '/_auth/app/vitals/'
    | '/_auth/app/patients/$patientId/growth'
    | '/_auth/app/appointments/$id/edit'
    | '/_auth/app/encounters/$encounterId/edit'
    | '/_auth/app/encounters/$id/edit'
    | '/_auth/app/immunizations/$id/edit'
    | '/_auth/app/immunizations/$immunizationId/edit'
    | '/_auth/app/labs/$labOrderId/edit'
    | '/_auth/app/patients/$patientId/edit'
    | '/_auth/app/patients/$patientId/encounters'
    | '/_auth/app/patients/$patientId/immunizations'
    | '/_auth/app/patients/$patientId/labs'
    | '/_auth/app/patients/$patientId/prescriptions'
    | '/_auth/app/patients/$patientId/vitals'
    | '/_auth/app/prescriptions/$id/edit'
    | '/_auth/app/prescriptions/$prescriptionId/edit'
    | '/_auth/app/staff/$staffId/edit'
    | '/_auth/app/encounters/$encounterId/'
    | '/_auth/app/immunizations/$immunizationId/'
    | '/_auth/app/labs/$labOrderId/'
    | '/_auth/app/prescriptions/$prescriptionId/'
    | '/_auth/app/staff/$staffId/'
    | '/_auth/app/patients/$patientId/growth/history'
    | '/_auth/app/patients/$patientId/growth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  BuilderRoute: typeof BuilderRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/about': {
      id: '/_guest/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof GuestAboutRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/privacy': {
      id: '/_guest/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof GuestPrivacyRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/support': {
      id: '/_guest/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof GuestSupportRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/terms': {
      id: '/_guest/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof GuestTermsRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/growth': {
      id: '/_auth/app/growth'
      path: '/growth'
      fullPath: '/app/growth'
      preLoaderRoute: typeof AuthAppGrowthRouteRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/analytics/': {
      id: '/_auth/app/analytics/'
      path: '/analytics'
      fullPath: '/app/analytics/'
      preLoaderRoute: typeof AuthAppAnalyticsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/appointments/': {
      id: '/_auth/app/appointments/'
      path: '/appointments'
      fullPath: '/app/appointments/'
      preLoaderRoute: typeof AuthAppAppointmentsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/appointments/$id': {
      id: '/_auth/app/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/app/appointments/$id'
      preLoaderRoute: typeof AuthAppAppointmentsIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/appointments/new': {
      id: '/_auth/app/appointments/new'
      path: '/appointments/new'
      fullPath: '/app/appointments/new'
      preLoaderRoute: typeof AuthAppAppointmentsNewRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/encounters/': {
      id: '/_auth/app/encounters/'
      path: '/encounters'
      fullPath: '/app/encounters/'
      preLoaderRoute: typeof AuthAppEncountersIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/encounters/$id': {
      id: '/_auth/app/encounters/$id'
      path: '/encounters/$id'
      fullPath: '/app/encounters/$id'
      preLoaderRoute: typeof AuthAppEncountersIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/encounters/new': {
      id: '/_auth/app/encounters/new'
      path: '/encounters/new'
      fullPath: '/app/encounters/new'
      preLoaderRoute: typeof AuthAppEncountersNewRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/growth/': {
      id: '/_auth/app/growth/'
      path: '/'
      fullPath: '/app/growth/'
      preLoaderRoute: typeof AuthAppGrowthIndexRouteImport
      parentRoute: typeof AuthAppGrowthRouteRoute
    }
    '/_auth/app/growth/new': {
      id: '/_auth/app/growth/new'
      path: '/new'
      fullPath: '/app/growth/new'
      preLoaderRoute: typeof AuthAppGrowthNewRouteImport
      parentRoute: typeof AuthAppGrowthRouteRoute
    }
    '/_auth/app/growth/record': {
      id: '/_auth/app/growth/record'
      path: '/record'
      fullPath: '/app/growth/record'
      preLoaderRoute: typeof AuthAppGrowthRecordRouteImport
      parentRoute: typeof AuthAppGrowthRouteRoute
    }
    '/_auth/app/immunizations/': {
      id: '/_auth/app/immunizations/'
      path: '/immunizations'
      fullPath: '/app/immunizations/'
      preLoaderRoute: typeof AuthAppImmunizationsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/immunizations/$id': {
      id: '/_auth/app/immunizations/$id'
      path: '/immunizations/$id'
      fullPath: '/app/immunizations/$id'
      preLoaderRoute: typeof AuthAppImmunizationsIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/immunizations/new': {
      id: '/_auth/app/immunizations/new'
      path: '/immunizations/new'
      fullPath: '/app/immunizations/new'
      preLoaderRoute: typeof AuthAppImmunizationsNewRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/labs/': {
      id: '/_auth/app/labs/'
      path: '/labs'
      fullPath: '/app/labs/'
      preLoaderRoute: typeof AuthAppLabsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/labs/new': {
      id: '/_auth/app/labs/new'
      path: '/labs/new'
      fullPath: '/app/labs/new'
      preLoaderRoute: typeof AuthAppLabsNewRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/patients/': {
      id: '/_auth/app/patients/'
      path: '/patients'
      fullPath: '/app/patients/'
      preLoaderRoute: typeof AuthAppPatientsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/patients/$patientId': {
      id: '/_auth/app/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/app/patients/$patientId'
      preLoaderRoute: typeof AuthAppPatientsPatientIdRouteRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/patients/$patientId': {
      id: '/_auth/app/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/app/patients/$patientId'
      preLoaderRoute: typeof AuthAppPatientsPatientIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/patients/new': {
      id: '/_auth/app/patients/new'
      path: '/patients/new'
      fullPath: '/app/patients/new'
      preLoaderRoute: typeof AuthAppPatientsNewRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/prescriptions/': {
      id: '/_auth/app/prescriptions/'
      path: '/prescriptions'
      fullPath: '/app/prescriptions/'
      preLoaderRoute: typeof AuthAppPrescriptionsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/prescriptions/new': {
      id: '/_auth/app/prescriptions/new'
      path: '/prescriptions/new'
      fullPath: '/app/prescriptions/new'
      preLoaderRoute: typeof AuthAppPrescriptionsNewRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/services/': {
      id: '/_auth/app/services/'
      path: '/services'
      fullPath: '/app/services/'
      preLoaderRoute: typeof AuthAppServicesIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/settings/': {
      id: '/_auth/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AuthAppSettingsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/staff/': {
      id: '/_auth/app/staff/'
      path: '/staff'
      fullPath: '/app/staff/'
      preLoaderRoute: typeof AuthAppStaffIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/staff/new': {
      id: '/_auth/app/staff/new'
      path: '/staff/new'
      fullPath: '/app/staff/new'
      preLoaderRoute: typeof AuthAppStaffNewRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/vitals/': {
      id: '/_auth/app/vitals/'
      path: '/vitals'
      fullPath: '/app/vitals/'
      preLoaderRoute: typeof AuthAppVitalsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/vitals/new': {
      id: '/_auth/app/vitals/new'
      path: '/vitals/new'
      fullPath: '/app/vitals/new'
      preLoaderRoute: typeof AuthAppVitalsNewRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/appointments/$id/edit': {
      id: '/_auth/app/appointments/$id/edit'
      path: '/edit'
      fullPath: '/app/appointments/$id/edit'
      preLoaderRoute: typeof AuthAppAppointmentsIdEditRouteImport
      parentRoute: typeof AuthAppAppointmentsIdRoute
    }
    '/_auth/app/encounters/$encounterId/': {
      id: '/_auth/app/encounters/$encounterId/'
      path: '/encounters/$encounterId'
      fullPath: '/app/encounters/$encounterId/'
      preLoaderRoute: typeof AuthAppEncountersEncounterIdIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/encounters/$encounterId/edit': {
      id: '/_auth/app/encounters/$encounterId/edit'
      path: '/encounters/$encounterId/edit'
      fullPath: '/app/encounters/$encounterId/edit'
      preLoaderRoute: typeof AuthAppEncountersEncounterIdEditRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/encounters/$id/edit': {
      id: '/_auth/app/encounters/$id/edit'
      path: '/edit'
      fullPath: '/app/encounters/$id/edit'
      preLoaderRoute: typeof AuthAppEncountersIdEditRouteImport
      parentRoute: typeof AuthAppEncountersIdRoute
    }
    '/_auth/app/immunizations/$id/edit': {
      id: '/_auth/app/immunizations/$id/edit'
      path: '/edit'
      fullPath: '/app/immunizations/$id/edit'
      preLoaderRoute: typeof AuthAppImmunizationsIdEditRouteImport
      parentRoute: typeof AuthAppImmunizationsIdRoute
    }
    '/_auth/app/immunizations/$immunizationId/': {
      id: '/_auth/app/immunizations/$immunizationId/'
      path: '/immunizations/$immunizationId'
      fullPath: '/app/immunizations/$immunizationId/'
      preLoaderRoute: typeof AuthAppImmunizationsImmunizationIdIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/immunizations/$immunizationId/edit': {
      id: '/_auth/app/immunizations/$immunizationId/edit'
      path: '/immunizations/$immunizationId/edit'
      fullPath: '/app/immunizations/$immunizationId/edit'
      preLoaderRoute: typeof AuthAppImmunizationsImmunizationIdEditRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/labs/$labOrderId/': {
      id: '/_auth/app/labs/$labOrderId/'
      path: '/labs/$labOrderId'
      fullPath: '/app/labs/$labOrderId/'
      preLoaderRoute: typeof AuthAppLabsLabOrderIdIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/labs/$labOrderId/edit': {
      id: '/_auth/app/labs/$labOrderId/edit'
      path: '/labs/$labOrderId/edit'
      fullPath: '/app/labs/$labOrderId/edit'
      preLoaderRoute: typeof AuthAppLabsLabOrderIdEditRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/patients/$patientId/edit': {
      id: '/_auth/app/patients/$patientId/edit'
      path: '/edit'
      fullPath: '/app/patients/$patientId/edit'
      preLoaderRoute: typeof AuthAppPatientsPatientIdEditRouteImport
      parentRoute: typeof AuthAppPatientsPatientIdRoute
    }
    '/_auth/app/patients/$patientId/encounters': {
      id: '/_auth/app/patients/$patientId/encounters'
      path: '/encounters'
      fullPath: '/app/patients/$patientId/encounters'
      preLoaderRoute: typeof AuthAppPatientsPatientIdEncountersRouteImport
      parentRoute: typeof AuthAppPatientsPatientIdRoute
    }
    '/_auth/app/patients/$patientId/growth': {
      id: '/_auth/app/patients/$patientId/growth'
      path: '/growth'
      fullPath: '/app/patients/$patientId/growth'
      preLoaderRoute: typeof AuthAppPatientsPatientIdGrowthRouteRouteImport
      parentRoute: typeof AuthAppPatientsPatientIdRoute
    }
    '/_auth/app/patients/$patientId/immunizations': {
      id: '/_auth/app/patients/$patientId/immunizations'
      path: '/immunizations'
      fullPath: '/app/patients/$patientId/immunizations'
      preLoaderRoute: typeof AuthAppPatientsPatientIdImmunizationsRouteImport
      parentRoute: typeof AuthAppPatientsPatientIdRoute
    }
    '/_auth/app/patients/$patientId/labs': {
      id: '/_auth/app/patients/$patientId/labs'
      path: '/labs'
      fullPath: '/app/patients/$patientId/labs'
      preLoaderRoute: typeof AuthAppPatientsPatientIdLabsRouteImport
      parentRoute: typeof AuthAppPatientsPatientIdRoute
    }
    '/_auth/app/patients/$patientId/prescriptions': {
      id: '/_auth/app/patients/$patientId/prescriptions'
      path: '/prescriptions'
      fullPath: '/app/patients/$patientId/prescriptions'
      preLoaderRoute: typeof AuthAppPatientsPatientIdPrescriptionsRouteImport
      parentRoute: typeof AuthAppPatientsPatientIdRoute
    }
    '/_auth/app/patients/$patientId/vitals': {
      id: '/_auth/app/patients/$patientId/vitals'
      path: '/vitals'
      fullPath: '/app/patients/$patientId/vitals'
      preLoaderRoute: typeof AuthAppPatientsPatientIdVitalsRouteImport
      parentRoute: typeof AuthAppPatientsPatientIdRoute
    }
    '/_auth/app/prescriptions/$id/edit': {
      id: '/_auth/app/prescriptions/$id/edit'
      path: '/prescriptions/$id/edit'
      fullPath: '/app/prescriptions/$id/edit'
      preLoaderRoute: typeof AuthAppPrescriptionsIdEditRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/prescriptions/$prescriptionId/': {
      id: '/_auth/app/prescriptions/$prescriptionId/'
      path: '/prescriptions/$prescriptionId'
      fullPath: '/app/prescriptions/$prescriptionId/'
      preLoaderRoute: typeof AuthAppPrescriptionsPrescriptionIdIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/prescriptions/$prescriptionId/edit': {
      id: '/_auth/app/prescriptions/$prescriptionId/edit'
      path: '/prescriptions/$prescriptionId/edit'
      fullPath: '/app/prescriptions/$prescriptionId/edit'
      preLoaderRoute: typeof AuthAppPrescriptionsPrescriptionIdEditRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/staff/$staffId/': {
      id: '/_auth/app/staff/$staffId/'
      path: '/staff/$staffId'
      fullPath: '/app/staff/$staffId/'
      preLoaderRoute: typeof AuthAppStaffStaffIdIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/staff/$staffId/edit': {
      id: '/_auth/app/staff/$staffId/edit'
      path: '/staff/$staffId/edit'
      fullPath: '/app/staff/$staffId/edit'
      preLoaderRoute: typeof AuthAppStaffStaffIdEditRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/patients/$patientId/growth/': {
      id: '/_auth/app/patients/$patientId/growth/'
      path: '/'
      fullPath: '/app/patients/$patientId/growth/'
      preLoaderRoute: typeof AuthAppPatientsPatientIdGrowthIndexRouteImport
      parentRoute: typeof AuthAppPatientsPatientIdGrowthRouteRoute
    }
    '/_auth/app/patients/$patientId/growth/history': {
      id: '/_auth/app/patients/$patientId/growth/history'
      path: '/history'
      fullPath: '/app/patients/$patientId/growth/history'
      preLoaderRoute: typeof AuthAppPatientsPatientIdGrowthHistoryRouteImport
      parentRoute: typeof AuthAppPatientsPatientIdGrowthRouteRoute
    }
  }
}

interface AuthAppGrowthRouteRouteChildren {
  AuthAppGrowthNewRoute: typeof AuthAppGrowthNewRoute
  AuthAppGrowthRecordRoute: typeof AuthAppGrowthRecordRoute
  AuthAppGrowthIndexRoute: typeof AuthAppGrowthIndexRoute
}

const AuthAppGrowthRouteRouteChildren: AuthAppGrowthRouteRouteChildren = {
  AuthAppGrowthNewRoute: AuthAppGrowthNewRoute,
  AuthAppGrowthRecordRoute: AuthAppGrowthRecordRoute,
  AuthAppGrowthIndexRoute: AuthAppGrowthIndexRoute,
}

const AuthAppGrowthRouteRouteWithChildren =
  AuthAppGrowthRouteRoute._addFileChildren(AuthAppGrowthRouteRouteChildren)

interface AuthAppAppointmentsIdRouteChildren {
  AuthAppAppointmentsIdEditRoute: typeof AuthAppAppointmentsIdEditRoute
}

const AuthAppAppointmentsIdRouteChildren: AuthAppAppointmentsIdRouteChildren = {
  AuthAppAppointmentsIdEditRoute: AuthAppAppointmentsIdEditRoute,
}

const AuthAppAppointmentsIdRouteWithChildren =
  AuthAppAppointmentsIdRoute._addFileChildren(
    AuthAppAppointmentsIdRouteChildren,
  )

interface AuthAppEncountersIdRouteChildren {
  AuthAppEncountersIdEditRoute: typeof AuthAppEncountersIdEditRoute
}

const AuthAppEncountersIdRouteChildren: AuthAppEncountersIdRouteChildren = {
  AuthAppEncountersIdEditRoute: AuthAppEncountersIdEditRoute,
}

const AuthAppEncountersIdRouteWithChildren =
  AuthAppEncountersIdRoute._addFileChildren(AuthAppEncountersIdRouteChildren)

interface AuthAppImmunizationsIdRouteChildren {
  AuthAppImmunizationsIdEditRoute: typeof AuthAppImmunizationsIdEditRoute
}

const AuthAppImmunizationsIdRouteChildren: AuthAppImmunizationsIdRouteChildren =
  {
    AuthAppImmunizationsIdEditRoute: AuthAppImmunizationsIdEditRoute,
  }

const AuthAppImmunizationsIdRouteWithChildren =
  AuthAppImmunizationsIdRoute._addFileChildren(
    AuthAppImmunizationsIdRouteChildren,
  )

interface AuthAppPatientsPatientIdGrowthRouteRouteChildren {
  AuthAppPatientsPatientIdGrowthHistoryRoute: typeof AuthAppPatientsPatientIdGrowthHistoryRoute
  AuthAppPatientsPatientIdGrowthIndexRoute: typeof AuthAppPatientsPatientIdGrowthIndexRoute
}

const AuthAppPatientsPatientIdGrowthRouteRouteChildren: AuthAppPatientsPatientIdGrowthRouteRouteChildren =
  {
    AuthAppPatientsPatientIdGrowthHistoryRoute:
      AuthAppPatientsPatientIdGrowthHistoryRoute,
    AuthAppPatientsPatientIdGrowthIndexRoute:
      AuthAppPatientsPatientIdGrowthIndexRoute,
  }

const AuthAppPatientsPatientIdGrowthRouteRouteWithChildren =
  AuthAppPatientsPatientIdGrowthRouteRoute._addFileChildren(
    AuthAppPatientsPatientIdGrowthRouteRouteChildren,
  )

interface AuthAppPatientsPatientIdRouteChildren {
  AuthAppPatientsPatientIdGrowthRouteRoute: typeof AuthAppPatientsPatientIdGrowthRouteRouteWithChildren
  AuthAppPatientsPatientIdEditRoute: typeof AuthAppPatientsPatientIdEditRoute
  AuthAppPatientsPatientIdEncountersRoute: typeof AuthAppPatientsPatientIdEncountersRoute
  AuthAppPatientsPatientIdImmunizationsRoute: typeof AuthAppPatientsPatientIdImmunizationsRoute
  AuthAppPatientsPatientIdLabsRoute: typeof AuthAppPatientsPatientIdLabsRoute
  AuthAppPatientsPatientIdPrescriptionsRoute: typeof AuthAppPatientsPatientIdPrescriptionsRoute
  AuthAppPatientsPatientIdVitalsRoute: typeof AuthAppPatientsPatientIdVitalsRoute
}

const AuthAppPatientsPatientIdRouteChildren: AuthAppPatientsPatientIdRouteChildren =
  {
    AuthAppPatientsPatientIdGrowthRouteRoute:
      AuthAppPatientsPatientIdGrowthRouteRouteWithChildren,
    AuthAppPatientsPatientIdEditRoute: AuthAppPatientsPatientIdEditRoute,
    AuthAppPatientsPatientIdEncountersRoute:
      AuthAppPatientsPatientIdEncountersRoute,
    AuthAppPatientsPatientIdImmunizationsRoute:
      AuthAppPatientsPatientIdImmunizationsRoute,
    AuthAppPatientsPatientIdLabsRoute: AuthAppPatientsPatientIdLabsRoute,
    AuthAppPatientsPatientIdPrescriptionsRoute:
      AuthAppPatientsPatientIdPrescriptionsRoute,
    AuthAppPatientsPatientIdVitalsRoute: AuthAppPatientsPatientIdVitalsRoute,
  }

const AuthAppPatientsPatientIdRouteWithChildren =
  AuthAppPatientsPatientIdRoute._addFileChildren(
    AuthAppPatientsPatientIdRouteChildren,
  )

interface AuthAppRouteRouteChildren {
  AuthAppGrowthRouteRoute: typeof AuthAppGrowthRouteRouteWithChildren
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppPatientsPatientIdRouteRoute: typeof AuthAppPatientsPatientIdRouteRoute
  AuthAppAppointmentsIdRoute: typeof AuthAppAppointmentsIdRouteWithChildren
  AuthAppAppointmentsNewRoute: typeof AuthAppAppointmentsNewRoute
  AuthAppEncountersIdRoute: typeof AuthAppEncountersIdRouteWithChildren
  AuthAppEncountersNewRoute: typeof AuthAppEncountersNewRoute
  AuthAppImmunizationsIdRoute: typeof AuthAppImmunizationsIdRouteWithChildren
  AuthAppImmunizationsNewRoute: typeof AuthAppImmunizationsNewRoute
  AuthAppLabsNewRoute: typeof AuthAppLabsNewRoute
  AuthAppPatientsPatientIdRoute: typeof AuthAppPatientsPatientIdRouteWithChildren
  AuthAppPatientsNewRoute: typeof AuthAppPatientsNewRoute
  AuthAppPrescriptionsNewRoute: typeof AuthAppPrescriptionsNewRoute
  AuthAppStaffNewRoute: typeof AuthAppStaffNewRoute
  AuthAppVitalsNewRoute: typeof AuthAppVitalsNewRoute
  AuthAppAnalyticsIndexRoute: typeof AuthAppAnalyticsIndexRoute
  AuthAppAppointmentsIndexRoute: typeof AuthAppAppointmentsIndexRoute
  AuthAppEncountersIndexRoute: typeof AuthAppEncountersIndexRoute
  AuthAppImmunizationsIndexRoute: typeof AuthAppImmunizationsIndexRoute
  AuthAppLabsIndexRoute: typeof AuthAppLabsIndexRoute
  AuthAppPatientsIndexRoute: typeof AuthAppPatientsIndexRoute
  AuthAppPrescriptionsIndexRoute: typeof AuthAppPrescriptionsIndexRoute
  AuthAppServicesIndexRoute: typeof AuthAppServicesIndexRoute
  AuthAppSettingsIndexRoute: typeof AuthAppSettingsIndexRoute
  AuthAppStaffIndexRoute: typeof AuthAppStaffIndexRoute
  AuthAppVitalsIndexRoute: typeof AuthAppVitalsIndexRoute
  AuthAppEncountersEncounterIdEditRoute: typeof AuthAppEncountersEncounterIdEditRoute
  AuthAppImmunizationsImmunizationIdEditRoute: typeof AuthAppImmunizationsImmunizationIdEditRoute
  AuthAppLabsLabOrderIdEditRoute: typeof AuthAppLabsLabOrderIdEditRoute
  AuthAppPrescriptionsIdEditRoute: typeof AuthAppPrescriptionsIdEditRoute
  AuthAppPrescriptionsPrescriptionIdEditRoute: typeof AuthAppPrescriptionsPrescriptionIdEditRoute
  AuthAppStaffStaffIdEditRoute: typeof AuthAppStaffStaffIdEditRoute
  AuthAppEncountersEncounterIdIndexRoute: typeof AuthAppEncountersEncounterIdIndexRoute
  AuthAppImmunizationsImmunizationIdIndexRoute: typeof AuthAppImmunizationsImmunizationIdIndexRoute
  AuthAppLabsLabOrderIdIndexRoute: typeof AuthAppLabsLabOrderIdIndexRoute
  AuthAppPrescriptionsPrescriptionIdIndexRoute: typeof AuthAppPrescriptionsPrescriptionIdIndexRoute
  AuthAppStaffStaffIdIndexRoute: typeof AuthAppStaffStaffIdIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppGrowthRouteRoute: AuthAppGrowthRouteRouteWithChildren,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppPatientsPatientIdRouteRoute: AuthAppPatientsPatientIdRouteRoute,
  AuthAppAppointmentsIdRoute: AuthAppAppointmentsIdRouteWithChildren,
  AuthAppAppointmentsNewRoute: AuthAppAppointmentsNewRoute,
  AuthAppEncountersIdRoute: AuthAppEncountersIdRouteWithChildren,
  AuthAppEncountersNewRoute: AuthAppEncountersNewRoute,
  AuthAppImmunizationsIdRoute: AuthAppImmunizationsIdRouteWithChildren,
  AuthAppImmunizationsNewRoute: AuthAppImmunizationsNewRoute,
  AuthAppLabsNewRoute: AuthAppLabsNewRoute,
  AuthAppPatientsPatientIdRoute: AuthAppPatientsPatientIdRouteWithChildren,
  AuthAppPatientsNewRoute: AuthAppPatientsNewRoute,
  AuthAppPrescriptionsNewRoute: AuthAppPrescriptionsNewRoute,
  AuthAppStaffNewRoute: AuthAppStaffNewRoute,
  AuthAppVitalsNewRoute: AuthAppVitalsNewRoute,
  AuthAppAnalyticsIndexRoute: AuthAppAnalyticsIndexRoute,
  AuthAppAppointmentsIndexRoute: AuthAppAppointmentsIndexRoute,
  AuthAppEncountersIndexRoute: AuthAppEncountersIndexRoute,
  AuthAppImmunizationsIndexRoute: AuthAppImmunizationsIndexRoute,
  AuthAppLabsIndexRoute: AuthAppLabsIndexRoute,
  AuthAppPatientsIndexRoute: AuthAppPatientsIndexRoute,
  AuthAppPrescriptionsIndexRoute: AuthAppPrescriptionsIndexRoute,
  AuthAppServicesIndexRoute: AuthAppServicesIndexRoute,
  AuthAppSettingsIndexRoute: AuthAppSettingsIndexRoute,
  AuthAppStaffIndexRoute: AuthAppStaffIndexRoute,
  AuthAppVitalsIndexRoute: AuthAppVitalsIndexRoute,
  AuthAppEncountersEncounterIdEditRoute: AuthAppEncountersEncounterIdEditRoute,
  AuthAppImmunizationsImmunizationIdEditRoute:
    AuthAppImmunizationsImmunizationIdEditRoute,
  AuthAppLabsLabOrderIdEditRoute: AuthAppLabsLabOrderIdEditRoute,
  AuthAppPrescriptionsIdEditRoute: AuthAppPrescriptionsIdEditRoute,
  AuthAppPrescriptionsPrescriptionIdEditRoute:
    AuthAppPrescriptionsPrescriptionIdEditRoute,
  AuthAppStaffStaffIdEditRoute: AuthAppStaffStaffIdEditRoute,
  AuthAppEncountersEncounterIdIndexRoute:
    AuthAppEncountersEncounterIdIndexRoute,
  AuthAppImmunizationsImmunizationIdIndexRoute:
    AuthAppImmunizationsImmunizationIdIndexRoute,
  AuthAppLabsLabOrderIdIndexRoute: AuthAppLabsLabOrderIdIndexRoute,
  AuthAppPrescriptionsPrescriptionIdIndexRoute:
    AuthAppPrescriptionsPrescriptionIdIndexRoute,
  AuthAppStaffStaffIdIndexRoute: AuthAppStaffStaffIdIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestAboutRoute: typeof GuestAboutRoute
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestPrivacyRoute: typeof GuestPrivacyRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
  GuestSignupRoute: typeof GuestSignupRoute
  GuestSupportRoute: typeof GuestSupportRoute
  GuestTermsRoute: typeof GuestTermsRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestAboutRoute: GuestAboutRoute,
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestPrivacyRoute: GuestPrivacyRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
  GuestSignupRoute: GuestSignupRoute,
  GuestSupportRoute: GuestSupportRoute,
  GuestTermsRoute: GuestTermsRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  BuilderRoute: BuilderRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
